In [21]:
# eigenvalue and eigenvector example

import numpy as np 

A = np.mat("3 1; 2 0")
print ("A : \n",A)

print("Eigenvalues :",np.linalg.eigvals(A))

eigenvalue,eigenvector = np.linalg.eig(A)

print("First tuple of eigen: ",eigenvalue)
print("Second tuple of eigen: ",eigenvector)
print(' ')

# Gram-Schmidt QR decompostion example

import numpy as np 
from scipy.linalg import qr

def QR_Decomposition(B):
  n, m = B.shape
  Q = np.empty((n, n))
  u = np.empty((m, n))

  u[:, 0] = B[:, 0]
  Q[:, 0] = u[:, 0] / np.linalg.norm(u[:, 0])

  for i in range(1, n):
    u[:, i] = B[:, i]
    for j in range(i):
      u[:, i] -= (B[:, i] @ Q[:, j]) * Q[:, j]
    Q[:, i] = u[:, i] / np.linalg.norm(u[:, i])
  R = np.zeros((n, m))
  for i in range(n):
    for j in range(i, m):
      R[i, j] = B[:, j] @ Q[:, i]
  return Q, R

def diag_sign(B):
  D = np.diag(np.sign(np.diag(B)))
  return D

def adjust_sign(Q, R):
  D = diag_sign(Q)
  Q[:, :] = Q @ D
  R[:, :] = D @ R
  return Q, R

B = np.array([[1.0, 1.0, 1.0], [1.9, 1.0, 1.0], [1.0, 1.9, 1.0]])
Q, R = adjust_sign(*QR_Decomposition(B))
print(Q, R)
print('')

# Orthogonality example

import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

vector1 = np.array([1, -2, 4])
vector2 = np.array([2, 5, 2])
dot_product = np.sum(vector1 * vector2)

if dot_product == 0:
  print("The two vectors are orthongonal.")

else:
  print("The two vectors are not orthongonal.")



 



A : 
 [[3 1]
 [2 0]]
Eigenvalues : [ 3.56155281 -0.56155281]
First tuple of eigen:  [ 3.56155281 -0.56155281]
Second tuple of eigen:  [[ 0.87192821 -0.27032301]
 [ 0.48963374  0.96276969]]
 
[[ 0.42220033 -0.11777028 -0.8988198 ]
 [ 0.80218063  0.51033789  0.30993786]
 [ 0.42220033 -0.8518717   0.30993786]] [[ 2.36854386  2.02656159  1.64658129]
 [ 0.         -1.22598863 -0.4593041 ]
 [ 0.          0.         -0.27894408]]

The two vectors are orthongonal.
